application: dr-magnethands
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

inbound_services:
- channel_presence

handlers:
- url: /serviceworker\.js
  static_files: serviceworker.js
  upload: serviceworker\.js

- url: /static
  static_dir: static

- url: /api/.*
  script: api.app

- url: /.*
  script: magnethands.app
